//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmEntities : DbContext
    {
        public PharmEntities()
            : base("name=PharmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<Sick> Sicks { get; set; }
        public DbSet<Treated> Treateds { get; set; }
        public DbSet<TreatedToVaccination> TreatedToVaccinations { get; set; }
        public DbSet<Vaccination> Vaccinations { get; set; }
    }
}
