//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treated
    {
        public Treated()
        {
            this.TreatedToVaccinations = new HashSet<TreatedToVaccination>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string PhoneNumber { get; set; }
        public byte[] ImageData { get; set; }
    
        public virtual Sick Sick { get; set; }
        public virtual ICollection<TreatedToVaccination> TreatedToVaccinations { get; set; }
    }
}
