//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination
    {
        public Vaccination()
        {
            this.TreatedToVaccinations = new HashSet<TreatedToVaccination>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> RecivingVaccine { get; set; }
        public string Manufacturer { get; set; }
    
        public virtual Manufacturer Manufacturer1 { get; set; }
        public virtual ICollection<TreatedToVaccination> TreatedToVaccinations { get; set; }
    }
}
